version: 2
jobs:
  build:
    machine: true
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: update os
          command: |
            sudo apt-get update && apt-get upgrade -y
      -run:
         name: install dependencies
         command: |
           sudo apt-get install apt-transport-https ca-certificates curl gnupg2 software-properties-common
      - run:
          name: build docker container for testing cron
          command: |
            docker build -t b00kwrm/tddd-cron .
      - run:
          name: run docker container
          command: |
            docker run -d b00kwrm/tddd-cron
      - run:
          name: check for running containers
          command: |
            docker ps
      - run:
          name: run docker mount script
          command: |
            sudo python3 get-docker-fs.py
            






    
       


