version: 2

jobs:
  build:
    docker:
      -image: circleci/python:latest


    steps:
      - checkout

      - run:
          name: build docker container with target os
          command: |
            docker build -t b00kwrm/tddd-cron .

     - run:
         name: download build log2timeline docker
         command: |
         docker pull log2timeline/plaso

    
       


