version: 2
jobs:
  build:
    machine: true
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: install python
          command: |
            ./install_python.sh
      - run:
          name: build docker container for testing cron
          command: |
            docker build -t b00kwrm/tddd-cron .
      - run:
          name: run docker container
          command: |
            docker run -d b00kwrm/tddd-cron
      - run:
          name: check for running containers
          command: |
            docker ps
      - run:
          name: run docker mount script
          command: |
            sudo python3 get-docker-fs.py
      - run:
          name: run docker log2timeline on /mnt
          command: |
            docker run -v /tmp/:/data log2timeline/plaso log2timeline.py /data/tddd-cron.plaso /mnt
            






    
       


