version: 2
jobs:
  build:
    machine: true
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: install python
          command: |
            ./install_python.sh
      - run:
          name: build docker container for testing cron
          command: |
            docker build -t b00kwrm/tddd-cron .
      - run:
          name: run docker container
          command: |
            docker run -d b00kwrm/tddd-cron
      - run:
          name: check for running containers
          command: |
            docker ps
      - run:
          name: run docker mount script
          command: |
            sudo python3 get-docker-fs.py
      - run:
          name: sleep for 3 minutes
          command: |
            sleep 180
      - run:
          name: pull plaso docker
          command: |
            docker pull log2timeline/plaso
      - run:
          name: run docker log2timeline on /mnt/var/log store the plaso file as circleci artifact
          command: |
            sudo docker run -v /mnt:/mnt -v /home/circleci/repo:/data log2timeline/plaso log2timeline.py --parsers linux,syslog /data/tddd-cron.plaso /mnt/var/log
      - store_artifacts:
          path: /home/circleci/repo/tddd-cron.plaso
          destination: tddd-cron.plaso

      - run:
          name: run docker psort on /data/tddd-cron.plaso store the xlsx file as circleci artifact
          command: |
            sudo docker run -v /mnt:/mnt -v /home/circleci/repo:/data log2timeline/plaso psort.py --analysis tagging --tagging-file /data/cron-tag.txt -o xlsx -w /data/tddd-cron-tagged.xlsx /data/tddd-cron.plaso
      - store_artifacts:
          path: /home/circleci/repo/tddd-cron-tagged.xlsx
          destination: tddd-cron-tagged.xlsx

      - run:
          name: run docker psort on /data/tddd-cron.plaso store the csv file as circleci artifact
          command: |
            sudo docker run -v /mnt:/mnt -v /home/circleci/repo:/data log2timeline/plaso psort.py --analysis tagging --tagging-file /data/cron-tag.txt -o l2tcsv -w /data/tddd-cron-tagged.csv /data/tddd-cron.plaso
      - store_artifacts:
          path: /home/circleci/repo/tddd-cron-tagged.csv
          destination: tddd-cron-tagged.csv
	  


            






    
       


