version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7.2
    working_directory: ~/repo
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true 
      - run:
          name: build docker container for testing cron
          command: |
            docker build -t b00kwrm/tddd-cron .
      - run:
          name: run docker container
          command: |
            docker run -d b00kwrm/tddd-cron
      - run:
          name: run docker container
          command: |
            docker ps
            






    
       


