version: 2
jobs:
  build:
    machine: true
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: install python
          command: |
            ./install_python.sh
      - run: 
          name: setup venv
          command: |
            /usr/local/bin/python3.7 -m venv venv
      - run: 
          name: activate venv
          command: |
            source venv/bin/activate
      - run: 
          name: install python dependencies
          command: |
            pip install paramiko
      - run:
          name: build docker container for testing cron
          command: |
            docker build -t b00kwrm/tddd-cron .
      - run:
          name: run docker container
          command: |
            docker run -d -p 8000:22 b00kwrm/tddd-cron
      - run:
          name: check for running containers
          command: |
            docker ps
      - run:
          name: run docker mount script
          command: |
            sudo /usr/local/bin/python3.7 get-docker-fs.py
      - run:
          name: sleep for 3 minutes
          command: |
            sleep 180
      - run:
          name: ls -lh
          command: |
            ls -lh
      - run:
         name: login with ssh to docker with python
         command: |
           python ssh_test.py
      - run:
          name: build custom plaso docker container
          command: |
            docker build -f customplaso_docker -t b00kwrm/customplaso .
      - run:
          name: run docker log2timeline on /mnt store the plaso file as circleci artifact
          command: |
            docker run -v /mnt:/mnt -v /home/circleci/repo:/data b00kwrm/customplaso log2timeline.py --parsers linux,syslog --logfile /data/plaso.log /data/tddd-cron.plaso /mnt/
      - store_artifacts:
          path: /home/circleci/repo/tddd-cron.plaso
          destination: tddd-cron.plaso
      - run:
          name: run docker psort on /data/tddd-cron.plaso store the xlsx file as circleci artifact;
          command: |
            docker run -v /mnt:/mnt -v /home/circleci/repo:/data b00kwrm/customplaso psort.py --analysis tagging --tagging-file /usr/local/share/plaso/tag_linux.txt -o xlsx -w /data/tddd-cron-tagged.xlsx /data/tddd-cron.plaso
      - store_artifacts:
          path: /home/circleci/repo/tddd-cron-tagged.xlsx
          destination: tddd-cron-tagged.xlsx
      - run:
          name: run docker psort on /data/tddd-cron.plaso store the csv file as circleci artifact
          command: |
            docker run -v /mnt:/mnt -v /home/circleci/repo:/data b00kwrm/customplaso psort.py --analysis tagging --tagging-file /usr/local/share/plaso/tag_linux.txt -o l2tcsv -w /data/tddd-cron-tagged.csv /data/tddd-cron.plaso
      - store_artifacts:
          path: /home/circleci/repo/tddd-cron-tagged.csv
          destination: tddd-cron-tagged.csv
      - run:
          name: test csv for tag
          command: |
            python test_for_tag.py

  deploy:
    machine: true
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: build custom plaso docker container
          command: |
            docker build -f customplaso_docker -t b00kwrm/customplaso .    
      - run:
          name: push to docker hub
          command: |
            echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
            docker push b00kwrm/customplaso
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
            






    
       


