version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7.2
    working_directory: ~/repo
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true 
      - run:
          name: run tests
          command: |
            docker build -t b00kwrm/tddd-cron .
      - run:
          name: inspect docker
          command: |
	    docker inspect --format='{{.GraphDriver.Data.LowerDir}}' $(docker ps -q)




    
       


