version: 2
jobs:
  build:
    machine: true
    working_directory: ~/repo
    steps:
      -run:
         name: update os
         command: |
           apt-get update && apt-get upgrade -y 
      - checkout
      - run:
          name: build docker container for testing cron
          command: |
            docker build -t b00kwrm/tddd-cron .
      - run:
          name: run docker container
          command: |
            docker run -d b00kwrm/tddd-cron
      - run:
          name: check for running containers
          command: |
            docker ps
      -run:
         name: update os and install python3
         command: |
         apt-get update && apt-get upgrade -y
      - run:
          name: run docker mount script
          command: |
            sudo python3 get-docker-fs.py
            






    
       


