version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.1
      - setup_remote_docker
          docker_layer_caching: true 
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: run tests
          command: |
            docker build -t b00kwrm/tddd-cron .


    
       


