# https://apihandyman.io/writing-openapi-swagger-specification-tutorial-part-2-the-basics/
swagger: "2.0"

info:
  verion: 1.0.0
  title: Simple API
  description: A simple API to learn how to write OpenAPI Specification.

schemes:
 - https
host: simple.api
basePath: /openapi101